### ISSUE TITLE
Error when building from docker

### ISSUE THREAD

**Issue by intosKai** [Cryptonomic/Conseil#495] opened 2019-08-01 12:43 UTC
I have error when build from docker
```
Aug 01, 2019 12:38:08 PM org.postgresql.Driver connect
SEVERE: Connection error: 
org.postgresql.util.PSQLException: Connection to localhost:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:265)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)
	at org.postgresql.Driver.makeConnection(Driver.java:450)
	at org.postgresql.Driver.connect(Driver.java:252)
	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
	at slick.jdbc.DataSourceJdbcDataSource.createConnection(JdbcDataSource.scala:68)
	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:494)
	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.postgresql.core.PGStream.<init>(PGStream.java:68)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:144)
	... 16 more

Aug 01, 2019 12:38:08 PM org.postgresql.Driver connect
SEVERE: Connection error: 
org.postgresql.util.PSQLException: Connection to localhost:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:265)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)
	at org.postgresql.Driver.makeConnection(Driver.java:450)
	at org.postgresql.Driver.connect(Driver.java:252)
	at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
	at slick.jdbc.DataSourceJdbcDataSource.createConnection(JdbcDataSource.scala:68)
	at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:494)
	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
	at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
	at slick.basic.BasicBackend$DatabaseDef.acquireSession(BasicBackend.scala:249)
	at slick.basic.BasicBackend$DatabaseDef.acquireSession$(BasicBackend.scala:248)
	at slick.jdbc.JdbcBackend$DatabaseDef.acquireSession(JdbcBackend.scala:37)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.postgresql.core.PGStream.<init>(PGStream.java:68)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:144)
	... 16 more

[info] TezosPlatformDiscoveryOperationsTest:
[info] tech.cryptonomic.conseil.tezos.TezosPlatformDiscoveryOperationsTest *** ABORTED ***
[info]   org.postgresql.util.PSQLException: Connection to localhost:5433 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
[info]   at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:265)
[info]   at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
[info]   at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)
[info]   at org.postgresql.Driver.makeConnection(Driver.java:450)
[info]   at org.postgresql.Driver.connect(Driver.java:252)
[info]   at slick.jdbc.DriverDataSource.getConnection(DriverDataSource.scala:101)
[info]   at slick.jdbc.DataSourceJdbcDataSource.createConnection(JdbcDataSource.scala:68)
[info]   at slick.jdbc.JdbcBackend$BaseSession.<init>(JdbcBackend.scala:494)
[info]   at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:46)
[info]   at slick.jdbc.JdbcBackend$DatabaseDef.createSession(JdbcBackend.scala:37)
[info]   ...
[info]   Cause: java.net.ConnectException: Connection refused (Connection refused)
[info]   at java.net.PlainSocketImpl.socketConnect(Native Method)
[info]   at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[info]   at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[info]   at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[info]   at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[info]   at java.net.Socket.connect(Socket.java:589)
[info]   at org.postgresql.core.PGStream.<init>(PGStream.java:68)
[info]   at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:144)
[info]   at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
[info]   at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:194)
[info]   ...
[info] Run completed in 1 minute, 24 seconds.
[info] Total number of tests run: 263
[info] Suites: completed 21, aborted 2
[info] Tests: succeeded 263, failed 0, canceled 0, ignored 0, pending 0
[info] *** 2 SUITES ABORTED ***
[error] Error during tests:
[error] 	tech.cryptonomic.conseil.tezos.TezosDatabaseOperationsTest
[error] 	tech.cryptonomic.conseil.tezos.TezosPlatformDiscoveryOperationsTest
[error] (Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 150 s, completed Aug 1, 2019 12:38:09 PM
The command '/bin/sh -c sbt clean assembly -J-Xss32m' returned a non-zero code: 1
```

**Comment by ivanopagano** [comment] 2019-08-01 18:26
hello there @intosKai , first a few preliminary questions:
- do you have a local instance of postgres running on the default port?
- do you have a local _docker_ instance of of postgres running on the default port?

**Comment by intosKai** [comment] 2019-08-01 19:21
I run postgres from docker-compose. I'm trying different ports, conseil from docker don't see postgres.

**Comment by intosKai** [comment] 2019-08-05 07:42
```
Docker version 18.09.7, build 2d0083d
OS: Ubuntu 18.04.2 LTS
```
Are you need more information?

**Comment by ivanopagano** [comment] 2019-08-09 09:07
Did you set up network in your compose file, as described [here](https://docs.docker.com/compose/networking/)?
I'm not the best docker expert of the world, just trying to help.

I see from the error log that the application is trying to lookup the db on `localhost`, which might not work between containers.

**Comment by tulpenhaendler** [comment] 2019-09-05 10:13
This is related to #534 
@ivanopagano the problem here is that this happens when building the image, before anything with docker-compose can happen.

after building, if done with docker-compose, one can access Postgres via the (Service-) name it was given in the compose file, or via container-name if both containers are on the same network, or if conseil is run with host-network option it can access an instance running on the docker-host via localhost.

But the problem now is that we cant build images in the first place ( unless you remove that specific test that relies on a DB prior to building )

**Comment by ivanopagano** [comment] 2019-09-05 10:25
Got it, thanks for taking time to explain it. We'll see how to fix the issue.

**Comment by jdsika** [comment] 2019-09-13 21:02
I have the same issue. Could someone point me in the direction of a "more extended" installation guide?
Reading this...
> 
>     do you have a local instance of postgres running on the default port?
>     do you have a local docker instance of of postgres running on the default port?
> 
>     Did you set up network in your compose file, as described here?
>
... tells me that there is stuff to do which is not mentioned in the readme or wiki?

**Comment by dorians** [comment] 2019-09-17 13:37
It's a duplicate of #534. Fix is ready and waiting for review: #551

**Comment by dorians** [comment] 2019-09-17 13:44
@jdsika, @tulpenhaendler could you please check if that fixes it?

**Comment by jdsika** [comment] 2019-09-21 21:12
```
[info] Run completed in 1 minute, 4 seconds.
[info] Total number of tests run: 271
[info] Suites: completed 21, aborted 2
[info] Tests: succeeded 271, failed 0, canceled 0, ignored 0, pending 0
[info] *** 2 SUITES ABORTED ***
[error] Error during tests:
[error]         tech.cryptonomic.conseil.tezos.TezosDatabaseOperationsTest
[error]         tech.cryptonomic.conseil.tezos.TezosPlatformDiscoveryOperationsTest
[error] (Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 215 s, completed Sep 21, 2019 9:07:32 PM
The command '/bin/sh -c sbt clean assembly -J-Xss32m' returned a non-zero code: 1
```

**Comment by dorians** [comment] 2019-09-23 11:02
Hey @jdsika, that PR was merged 5 days ago. Could you check if you have the same error on the master branch or if your branch is up to date with the current master?

**Comment by jdsika** [comment] 2019-09-23 19:15
```
git reset --hard origin/master
HEAD is now at e6217395 Merge pull request #551 from Cryptonomic/bugfix/534-docker-build-fails
```


```
[info] Run completed in 1 minute, 9 seconds.
[info] Total number of tests run: 271
[info] Suites: completed 21, aborted 2
[info] Tests: succeeded 271, failed 0, canceled 0, ignored 0, pending 0
[info] *** 2 SUITES ABORTED ***
[error] Error during tests:
[error]         tech.cryptonomic.conseil.tezos.TezosDatabaseOperationsTest
[error]         tech.cryptonomic.conseil.tezos.TezosPlatformDiscoveryOperationsTest
[error] (Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 223 s, completed Sep 23, 2019 7:14:40 PM
The command '/bin/sh -c sbt clean assembly -J-Xss32m' returned a non-zero code: 1
```

**Comment by jdsika** [comment] 2019-09-23 19:16
> 
> 
> Hey @jdsika, that PR was merged 5 days ago. Could you check if you have the same error on the master branch or if your branch is up to date with the current master?

I tried again and did a hard reset. Same issue as before. Any prerequisites?

**Comment by jdsika** [comment] 2019-10-05 19:27
@dorians bump

anyone trying to fix this? What should I try to debug? does the node need to be fully bootstrapped? is there anything I might have forgotten to install?

**Comment by ivanopagano** [comment] 2019-10-08 12:32
Hello @jdsika, sorry for the long silence but we're a bit short of people temporarily.

You're not actually expected to have anything prepared ahead-of-time for the image to be correctly built, and I cannot reproduce your error.

Can I ask for you to update once again to latest `master`, provide more information on your local setup (machine, os, docker version, ...) and finally describe exactly what command did you try to make it fail as you reported?

**Comment by jdsika** [comment] 2019-10-14 15:53
```
git fetch origin
git pull
docker system prune -a
docker build -t conseil .
```
building... let's see

**Comment by ivanopagano** [comment] 2019-10-17 09:55
@jdsika I have no real update for now, only verified that the issue doesn't seem to affect macos users, but is reproducible on ubuntu.

Will keep you posted

**Comment by jdsika** [comment] 2019-10-17 10:30
> 
> 
> @jdsika I have no real update for now, only verified that the issue doesn't seem to affect macos users, but is reproducible on ubuntu.
> 
> Will keep you posted

I am patiently waiting until I can use conseil ;)

**Comment by dorians** [comment] 2019-10-18 12:20
@jdsika just to clarify, the command you're using is: `docker build -t conseil .`?

**Comment by jdsika** [comment] 2019-10-18 12:25
yes, as stated above. Running it from the conseil directory

**Comment by ivanopagano** [comment] 2019-10-18 15:12
> > @jdsika I have no real update for now, only verified that the issue doesn't seem to affect macos users, but is reproducible on ubuntu.
> > Will keep you posted
> 
> I am patiently waiting until I can use conseil ;)

@jdsika 
I can suggest you make a simple hack and check if it solves your problem

Try removing the files listed as failing tests from your project sources.
You should find them here:
- `src/test/scala/tech/cryptonomic/conseil/tezos/ApiOperationsTest.scala`
- `src/test/scala/tech/cryptonomic/conseil/tezos/TezosDatabaseOperationsTest.scala`
- `src/test/scala/tech/cryptonomic/conseil/tezos/TezosPlatformDiscoveryOperationsTest.scala`

Then you retry building the image and let me know

**Comment by jdsika** [comment] 2019-10-29 10:29
```
Successfully built 9f685575aa1a
Successfully tagged conseil:latest
```

@ivanopagano using your little hack and the latest mainnet

**Comment by ivanopagano** [comment] 2019-10-29 11:30
Thanks @jdsika we're already working on a more robust solution, but your "experiment" helped me verify my assumptions.

**Comment by jdsika** [comment] 2019-10-29 11:33
Good, unfortunately the documentation on how to create the configs. How to properly configure it and a lot more is not documented in a straight forward way... At least for me to understand :/
There is also no mention of if this works with an archive node in mainnet-staging with the new backend?

**Comment by ivanopagano** [comment] 2019-10-29 12:49
Thank you for the useful feedback

**Comment by jdsika** [comment] 2019-10-30 11:53
@ivanopagano Maybe you could use the Nomadic Labs Indexer Documentation as a reference and I am outing myself here:
I got that thing running yesterday after 2hours and a million questions in this [ticket](https://gitlab.com/nomadic-labs/tezos-indexer/issues/9#note_237512561). It is very well documented and I still encountered a lot of problems.

The premise should be:
"I installed a new Ubuntu, installed the Tezos (archive) node from BRANCHNAME and want to start with the indexer. I have no idea about nothing and need the command line instructions to get the minimum running.
Using an example config which works for the example and directs to the more detailed instructions on how to do configurations etc. But it should take a newby not more then half a day of hustling to get your product running, right?

**Comment by vishakh** [comment] 2020-04-08 02:41
We have updated the docs on the Conseil wiki. Please try them out if you are still interested.

**Closed by vishakh** 2020-04-08 02:41 UTC
