### ISSUE TITLE
Tweaks to Conseil API v2

### ISSUE THREAD

**Issue by ba205** [Cryptonomic/Conseil#235] opened 2019-01-24 20:22 UTC
- [ ] The entities route redundantly returns the network name, even though the route looks like <...network/entities...>, so the user already knows by the time they are using this route what network they are on. This should be removed.
- [ ] The "timestamp" field has a cardinality when returned by an entities query. This should be removed, because the cardinality of "timestamp" is necessarily the length of the table it is in, and will be expensive to compute.
- [ ] Right now, we parse the "script" and "params" fields from the Tezos Node using Jackson into a Scala object, and we write that to the blocks/accounts tables. For now, let's write the raw json returned by the Tezos node instead.
- [ ] Specifying no fields in the json payload should return all columns for that table. Right now, it only returns some of them when that is the case.
- [ ] Certain fields do not work for queries, such as "source" and "destination" for accounts table queries.
- [ ] When trying to query all unique predecessors from the blocks table, the server returned an error instead of returning the specified elements

**Comment by anonymoussprocket** [comment] 2019-01-24 21:57
In general, unless explicitly allowed (which is something we have not discussed yet), numeric and date (timestamp) fields should not return cardinality.

**Comment by vishakh** [comment] 2019-01-25 04:14
Perhaps the third point, i.e. the one about `script` and `params` should be a separate ticket.

**Comment by piotrkosecki** [comment] 2019-01-25 10:56
`Specifying no fields in the json payload should return all columns for that table. Right now, it only returns some of them when that is the case.`
`Certain fields do not work for queries, such as "source" and "destination" for accounts table queries.`
I believe the issue is with columns with null values and empty strings - they are not being put into json.  

I want to confirm that is an expected behaviour to return nulls/empty strings for empty columns.

**Comment by piotrkosecki** [comment] 2019-01-25 14:51
`When trying to query all unique predecessors from the blocks table, the server returned an error instead of returning the specified elements` 
Distinct count of `predecessor` I've got locally is `177498`, so it is considered high cardinality field, and `metadata` endpoint is not supposed to return distinct values for those kinds of fields.
Unless you are using `data` endpoint which works ok in my case. If it's a case could you paste me a request/response @ba205 ?

**Comment by piotrkosecki** [comment] 2019-08-08 17:05
Issues were resolved in PR below:
https://github.com/Cryptonomic/Conseil/pull/239

**Closed by piotrkosecki** 2019-08-08 17:05 UTC
Labels: bug
